on:
  push:
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: actions/checkout@v4

       - name:list of the file
        run: ls
       - name: gradlew
        run :  ./gradlew test
